# Generated by Django 3.0.8 on 2020-08-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.CharField(default='Old field, no author', max_length=255),
            preserve_default=False,
        ),
    ]
